//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditoriasCiudadanas.Mobile.Core.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuditoriasCiudadanas.Mobile.Core.Assets.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ha olvidado la contraseña?.
        /// </summary>
        internal static string AppLogin_BtnForgotPassword {
            get {
                return ResourceManager.GetString("AppLogin_BtnForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string AppLogin_BtnLogin {
            get {
                return ResourceManager.GetString("AppLogin_BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string AppLogin_BtnSignUp {
            get {
                return ResourceManager.GetString("AppLogin_BtnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        internal static string AppLogin_EntryEmail {
            get {
                return ResourceManager.GetString("AppLogin_EntryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string AppLogin_EntryPassword {
            get {
                return ResourceManager.GetString("AppLogin_EntryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparencia por Colombia
        ///TODOS LOS DERECHOS RESERVADOS
        ///2018.
        /// </summary>
        internal static string AppMainPage_Footer {
            get {
                return ResourceManager.GetString("AppMainPage_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somos una herramienta para la gestión transparente de la actividad, desde la explotación de los recursos naturales, hasta la finaciación y ejecución de los proyectos de inversión que benefician a todos los colombianos.
        /// </summary>
        internal static string AppMainPage_Message {
            get {
                return ResourceManager.GetString("AppMainPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido!.
        /// </summary>
        internal static string AppMainPage_Title {
            get {
                return ResourceManager.GetString("AppMainPage_Title", resourceCulture);
            }
        }
    }
}
